### ISSUE TITLE
Define autoincrement with primary key and big integer for migration file

### ISSUE THREAD

**Issue by itsursujit** [cycle/migrations#11]
I'm finding difficulty to define the Auto increment with primary key for big integers?

The documentation is not mentioning something like that.

Please help

**Comment by wolfy-j** [comment]
Try `bigPrimary`.

**Comment by wolfy-j** [comment]
https://spiral.dev/docs/database-declaration#primary-index

**Comment by itsursujit** [comment]
Great! Thanks
That works...

I've other issues on Spiral App. Trying to find solution..
