### ISSUE TITLE
Pimcore - Syntax error or access violation: 1305 FUNCTION db_name.PLUGIN_CMF_COLLECT_OBJECT_SEGMENT_ASSIGNMENTS does not exist in

### ISSUE THREAD

**Issue by salmanshafiq8630** [cycle/migrations#42]
I have a pimcore (6.8) setup in our local system with apache2, php7.4 with all permision, mysql (8) ubuntu from a live site for version upgrade. This website in working with live but not working in our local system. When i login admin panel with this website in local. Then working perfectly. But when open any page in frontend then showing "Oops ... Sorry, the page you're looking for has gone."

And showing in dashboard when load any document but data in showing [enter image description here](https://i.stack.imgur.com/dIoZu.png) [enter image description here](https://i.stack.imgur.com/WjVqr.png)

Timestamp: Mon Dec 05 2022 15:00:45 GMT+0530 (India Standard Time) Status: 500 | Internal Server Error URL: /admin/customermanagementframework/segment-assignment/inheritable-segments?id=65&type=document&_dc=1670232645843 Method: GET Message: Database error, see logs for details

Logs Details- Syntax error or access violation: 1305 FUNCTION db_name.PLUGIN_CMF_COLLECT_OBJECT_SEGMENT_ASSIGNMENTS does not exist in

**Comment by roxblnfk** [comment]
As i can see the pincore [uses Doctrine](https://github.com/pimcore/pimcore/blob/11.x/composer.json#L53-L59), not Cycle.

Are you sure that issue has been created in the right place?

**Comment by roxblnfk** [comment]
Closed because of https://github.com/pimcore/pimcore/discussions/13734

**Comment by salmanshafiq8630** [comment]
{
"name": "pimcore/demo",
"type": "project",
"description": "Black Business Atlas",
"license": "GPL-3.0-or-later",
"config": {
"optimize-autoloader": true,
"sort-packages": true
},
"require": {
"php": ">=7.2",
"heidelpay/heidelpay-php": "1.2.5.1",
"hwi/oauth-bundle": "^1.3",
"knplabs/knp-paginator-bundle": "^5.4",
"php-http/guzzle6-adapter": "^2.0",
"php-http/httplug-bundle": "^1.2",
"pimcore/customer-management-framework-bundle": "^2.2",
"pimcore/data-hub": "dev-master",
"pimcore/pimcore": "~6.8.0",
"pimcore/web2print-tools-bundle": "^3.1",
"stripe/stripe-php": "^7.79",
"symfony/uid": "^5.2",
"twig/intl-extra": "^3.3"
},
"require-dev": {
"cache/integration-tests": "^0.16.0",
"codeception/codeception": "~2.4.5"
},
"autoload": {
"psr-4": {
"": ["src/"],
"Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
"Pimcore\\Model\\Object\\": "var/classes/Object",
"Website\\": "legacy/website/lib"
},
"classmap": [
"app/AppKernel.php"
]
},
"scripts": {
"post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
"post-install-cmd": [
"Pimcore\\Composer::postInstall",
***@***.***"
],
"post-update-cmd": [
"Pimcore\\Composer::postUpdate",
***@***.***",
"Pimcore\\Composer::executeMigrationsUp",
***@***.***"
],
"pimcore-scripts": [
"Pimcore\\Composer::clearCache",
"Pimcore\\Composer::installAssets"
]
},
"extra": {
"symfony-app-dir": "app",
"symfony-bin-dir": "bin",
"symfony-var-dir": "var",
"symfony-web-dir": "web",
"symfony-tests-dir": "tests",
"symfony-assets-install": "relative"
}
}
