### ISSUE TITLE
Table prefix doesn't work

### ISSUE THREAD

**Issue by BaBL86** [cycle/migrations#47]
I'm using cycle in Yii3 application, cycle/migration 4.0.1

Config:

```php
        'dbal' => [
            'databases' => [
                'primary' => [
                    'driver'  => 'mysql',
                    'prefix'  => 'primary_'
                ],
                'default' => ['connection' => 'mysql'],
            ],
        ],

        'migrations' => [
            'directory' => '@root/migrations',
            'namespace' => 'App\\Migration',
            'table' => 'migration',
            'safe' => false,
        ],
```

Migration:
```php
    public function up(): void
    {
        $this->table('user')
            ->addColumn('id', 'primary')
            ->addColumn('status_id', 'integer', ['length' => 1])
            ->addColumn('created_at', 'timestamp')
            ->addColumn('token', 'string', ['length' => 32])
            ->addColumn('login', 'string', ['length' => 16])
            ->addColumn('password_hash', 'string', ['length' => 32])
            ->create();
    }
```

What I expect:
1. created empty table `primary_migration`
2. created table `primary_user`

Result:
1. created empty table `primary_migration`
2. migration filled in table `migration` (without prefix)
4. table `user` created without prefix

**Comment by msmakouz** [comment]
@BaBL86 Hi, I was unable to reproduce the issue using the Spiral Framework.
I created a test application, added a test entity, and set up a database connection and a prefix. Generated and executed the migration:

https://github.com/msmakouz/migrations-prefix

<img width="465" alt="111" src="https://user-images.githubusercontent.com/67324318/224968823-f8c7c1b5-eec6-4238-9c5d-e92d8eb4ebd2.png">

Please try to reproduce the issue using the Spiral Framework. When using Yii 3, the issue may be at the level of integration of the framework and database and migrations.

**Comment by roxblnfk** [comment]
Feel free to reopen the issue if the problem is still actual
