### ISSUE TITLE
Can't run migration: Invalid migration filename

### ISSUE THREAD

**Issue by kamilwylegala** [cycle/migrations#56]
Hey! I already integrated `cycle/orm` in my project. Library is great!

Now I'm trying to add `cycle/migrations` to my application, I just want to create migrations manually like in this [example](https://cycle-orm.dev/docs/database-migrations#create-a-migration).

I stumbled upon one issue. When I try to run migration it reports an error:

```
  [Cycle\Migrations\Exception\RepositoryException]                                                           
  Invalid migration filename '/var/www/html/app/Framework/CycleOrm/Migrations/MyMigrationMigration.php' 
```

My configuration is following:
```php
use Cycle\Migrations\Config\MigrationConfig;
use Cycle\Migrations\FileRepository;
use Cycle\Migrations\Migrator;

//I get here valid DBAL instance, already used in production code.
 $dbal = $this->DBALFactory->create();

 $config = new MigrationConfig(
     [
         'directory' => ROOT.'/app/Framework/CycleOrm/Migrations',
         'table' => 'migrations',
         'safe' => false,
      ]
 );

$migrator = new Migrator(
  $config,
  $dbal,
  new FileRepository($config)
);

//This part is OK, "migrations" table is created in database.
$migrator->configure();
```

Then I put to `app/Framework/CycleOrm/Migrations` directory following file:

```php
use Cycle\Migrations\Migration;

class MyMigrationMigration extends Migration
{

    public function up()
    {
        // TODO: Implement up() method.
    }

    public function down()
    {
        // TODO: Implement down() method.
    }
}
```

And I invoke following on `$migrator` instance from first code section:
```php
$migrator->run(new Capsule($dbal->database()));
```

Migrator throws an exception:
```
[Cycle\Migrations\Exception\RepositoryException]                                                           
Invalid migration filename '/var/www/html/app/CakeFramework/CycleOrm/Migrations/MyMigrationMigration.php'
```

Could you advise?

**Comment by roxblnfk** [comment]
Hi
Migration files should follow a certain pattern. The name starts with a timestamp including microseconds. This is necessary for the correct sorting of migrations.
Then, there are some numbers and the name of the database. These values might be optional (I'm not sure)


![Image](https://github.com/cycle/migrations/assets/4152481/c9bf2c22-f331-49f8-b5a0-e5b8ef8a90a5)

**Comment by roxblnfk** [comment]
If you're not using ready-made bridges, you can copy ready-made console commands for creating migrations. For example, like here:

https://github.com/yiisoft/yii-cycle/blob/master/src/Command/Migration/CreateCommand.php

**Comment by kamilwylegala** [comment]
Thank you :rocket:  

It did the job. I thought that both: file name + class name must be the same. After I changed `MyMigrationMigration` to `20231211.144340_1_default_test.php` it worked.
